### ISSUE TITLE
Placement of overlay divs is wrong

### ISSUE THREAD

**Issue by wijnen** [Aeva/m.grl#178] opened 2015-12-27 09:37 UTC
Overlay divs (including from #166 / #167 ) are not correctly placed. There are multiple problems:

  - a css percentage for a vertical length uses the page _width_ as reference; the code assumes height.
  - absolute coordinates are relative to the page, not the parent element.
  - some things are incorrectly computed, so the results are wrong.

I can't technically claim issues here, so I'll do that socially: I'm working on this, please wait for my pull request.

**Comment by wijnen** [comment] 2016-01-02 17:10
I have a working implementation (with minor issues), but it's based on #167, not master. Do you want me to rebase it (I don't know when I have time for doing that properly), or shall I just commit it there?

**Comment by Aeva** [comment] 2016-01-04 18:41
building it off #167 is fine, since hopefully we'll be merging that in soon

**Comment by wijnen** [comment] 2016-01-04 21:06
Ok, I have a new branch in my fork named overlay.

It uses absolute positioning in pixels from the top left page corner, so it needs the offset of the overlay div.  I have not found a way to get that other than the recursive approach I use, which is potentially slow.  In reality it's not normally a problem, because the overlay div is either absolutely positioned itself, or pretty close to the root of the tree.  But it isn't nice.

If you know how to get the rotation and scale of the node in the view, please fill in and enable the transform.

**Comment by Aeva** [comment] 2016-01-05 04:42
Huh.  So I went and tested this out against my current local build (not your fork), and that the overlay seems to work fine.  I tested with this demo http://mgrl.midnightsisters.org/demos/object_selection/, removed the full screen mechanism and made sure the canvas div was centered.  I did notice, however, that if the canvas element is moved or etc after the overlay is created, the two fall out of sync with one another.

I noticed in your new branch, the code still references please.gl.canvas, so maybe that could be cause for it to bork out when using the dom renderer?  Not entirely sure, just a hunch.

The way the overlay thing was designed to work was to mimic the placement of the canvas element so that it appears above while not being a child to the canvas element.  The reason for this is that all children to the canvas element are only displayed when canvas isn't actually supported.  From then, all of the children to the overlay div can just use absolute positioning to simulate being relative to the canvas, as you might expect it should behave.

I think I need to make a 2D test case to test this with (and make it a canonical demo) so I can establish what is broken and what behaviors need to be changed.  I think I will fork the "flat rendering demo" for this purpose.

A side thought: my changes to your fork made it so you could disable either renderer at compile time, so I could also test this further by removing all of the gl-specific code and see what still works.

Unfortunately this is looking to be a busy month for me >_< but I will try to make this a priority so that we can merge your pull request into master soon!

**Comment by wijnen** [comment] 2016-01-05 08:20
The idea behind using a div and not the canvas as the parent is good, but it doesn't work the way you describe it, because position:absolute elements ignore their parent (for positioning purposes) and are positioned with respect to the page (which shows by them having the body element as their offsetParent; that also means my recursive function is not a performance problem if the overlay div is position:absolute).

I test with some code which can get scroll bars and if they are not all the way at the top, the old code puts things in the wrong position.  This is because getBoundingClientRect returns screen coordinates, not page coordinates.  Now I'm typing this, I think this can be used to replace the recursive function with two of those calls; one for the overlay and one for the body.

As for please.gl.canvas, that is only referenced in __{create,align}_canvas_overlay. I left them in there on purpose, because those are only called for gl contexts.  Well, align is also used in add_autoscale, that should probably work for dom as well.  But even with autoscale, it shouldn't align anything, because there isn't anything to align to.

As for the sync: I didn't touch that, I think?  Perhaps I accidentally removed an align function from the pipeline?  It shouldn't be there for dom (because there's nothing to align to), but it should for the gl renderer, I think.

**Comment by Aeva** [comment] 2016-01-06 19:42
So, I'm not sure if you're referring to the CSS spec or how M.GRL, so a real quick point of clarification:
if you have a parent element and a child element, and they are both set to use absolute positioning (and none of the parent's ancestors are), the parent will be absolute positioned relative to the top left corner of the document, whereas the child will be absolute positioned relative to the top left corner of its parent.  MDN defines absolute positioning [here](https://developer.mozilla.org/en-US/docs/Web/CSS/position) as:
> Do not leave space for the element. Instead, position it at a specified position relative to its closest positioned ancestor or to the containing block. Absolutely positioned boxes can have margins, they do not collapse with any other margins.

So, getBoundingClientRect is used to get the position and size of the canvas in terms of screen coordinates, so that we can position the overlay div to match.  This is absolutely necessary because this tells us the final computation for that element inclusive of stuff like using css to scale things and so on.  Everything that claims the overlay div as an ancestor should use absolute positioning to be relative to the top left corner of the overlay div.  Matrices should be used to convert from the game's coordinate space to "canvas space", which is easy because that is provided by the camera object and an object's world matrix already for GL to use.

The above two paragraphs are the actual browser spec works, and then how M.GRL is *supposed* to be using them.

**Comment by wijnen** [comment] 2016-01-06 23:54
I misunderstood position:absolute, apparently. Confusingly, position:static (the default) results in an element that is not "positioned", so in that case the reference is the body, otherwise it is the parent (or some other ancestor). I don't like to test for this in the code, it is too fragile.  So instead, the overlay div for the dom renderer could be forced to absolute positioning.  The easiest way to do this is by using the same system in the gl renderer: let m.grl create the div and align it to some other element.  I found that I often want a 2-D canvas below the overlay anyway, so that would be a suitable element.

**Comment by wijnen** [comment] 2016-01-07 12:35
I think I have it figured out. However, now I'm using __create_canvas_overlay, which seems to cause my click events to stop working. I don't know why they did work before, but now I'm setting style.pointerEvents to auto on the divs that need clicking and everything works fine. I was thinking of adding picking support as well, which would be trivial: every overlayed element gets its own pointer events.

I've pushed the new code (without picking support) to the overlay branch.

**Comment by Aeva** [comment] 2016-01-07 19:14
cool!  I will take a look at it soon :)

**Comment by Aeva** [comment] 2016-01-17 02:24
fixed in current master

**Closed** 2016-01-17 02:24 UTC
Labels: bug
